[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[mongo]
dataBaseURL = "localhost/owtdb" #default: "localhost/owtdb"

[cluster]
name = "owt-cluster"

[sip_portal]
#enable_grpc = true
