[console]
#configuration for the management-console
keystorePath = "./cert/certificate.pfx"
ssl = true #default: true
port = 3300 #default: 3300, port of manage console server

[api]
#configuration of management-api server
#secure = true #if server certificate is verified, set it to true.
host = "https://localhost:3000" #default "http://localhost:3000", specify "http" or "https" server here.