[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[manager]
name = "owt-cluster"

#The time for cluster manager getting ready to handle the incoming 'schedule' requirements.
initial_time = 6000 #ms

#The interval of checking the attendences of all cluster workers.
check_alive_interval = 1000 #ms

#The threshold count of consecutive absences after which the corresponding cluster workers will be deleted.
check_alive_count = 3

#The default reservation time if not specified in the scheduling requirement.
schedule_reserve_time = 60000 #ms

# Setup as GRPC server
enable_grpc = true
grpc_host = "localhost"
grpc_port = 10080

[strategy]
general = "last-used"
portal = "last-used"
conference = "last-used"
webrtc = "last-used"
sip = "round-robin"
streaming = "round-robin"
recording = "randomly-pick"
audio = "most-used"
video = "least-used"
analytics = "least-used"
