[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[manager]
name = "owt-cluster"
#Set its value to the number of cluster manager instancesï¼Œsuggest odd number
totalNode = 1 #node become leader when got vote gt totalNode/2

#electTimeout specifies the time in candidate state without contact from a leader before we attempt an election.
electTimeout = 1000 #ms

#leaderLeaseTimeout is used to control how long the "lease" lasts for being the leader without being able to contact a quorum of nodes. If we reach this interval without contact, we will step down as leader.
leaderLeaseTimeout = 500 #ms

#heartbeatTimeout specifies the time in follower state without contact from a leader before we attempt an election.
heartbeatTimeout = 1000 #ms

#The time for cluster manager getting ready to handle the incoming 'schedule' requirements.
initial_time = 6000 #ms

#The interval of checking the attendences of all cluster workers.
check_alive_interval = 1000 #ms

#The threshold count of consecutive absences after which the corresponding cluster workers will be deleted.
check_alive_count = 3

#The default reservation time if not specified in the scheduling requirement.
schedule_reserve_time = 60000 #ms

# Setup as GRPC server
#enable_grpc = true
#grpc_host = "localhost:10080"

[strategy]
general = "last-used"
portal = "last-used"
conference = "last-used"
webrtc = "last-used"
sip = "round-robin"
streaming = "round-robin"
recording = "randomly-pick"
audio = "most-used"
video = "least-used"
analytics = "least-used"
eventbridge = "last-used"
mediabridge = "last-used"

[cascading]
enabled = false #disable cascading feature by default
url = "none"   #default none:not connect to cascading cloud, specify cloud service url for the cluster to register to cloud
region = "BJ"
clusterID = "" #A unique cluster ID reporting to cascading cloud
